#ifndef OPENNPUX_CORAL_MOBILENET_H
#define OPENNPUX_CORAL_MOBILENET_H

#include <stdint.h>

#define OPENNPUX_CORAL_MOBILENET_MAGIC UINT32_C(0x4e504d42)
#define OPENNPUX_CORAL_MOBILENET_VERSION UINT32_C(1)
#define OPENNPUX_CORAL_MOBILENET_ARENA_SIZE UINT32_C(0x00400000)
#define OPENNPUX_CORAL_MOBILENET_MAILBOX_OFFSET UINT32_C(0x00400000)
#define OPENNPUX_CORAL_MOBILENET_OUTPUT_COUNT UINT32_C(5)

#define OPENNPUX_CORAL_MOBILENET_STARTED UINT32_C(1)
#define OPENNPUX_CORAL_MOBILENET_TENSORS_READY UINT32_C(2)
#define OPENNPUX_CORAL_MOBILENET_COMPLETE UINT32_C(3)
#define OPENNPUX_CORAL_MOBILENET_ERROR UINT32_C(0x80000000)

#define OPENNPUX_CORAL_MOBILENET_ERROR_NONE UINT32_C(0)
#define OPENNPUX_CORAL_MOBILENET_ERROR_ALLOCATE UINT32_C(1)
#define OPENNPUX_CORAL_MOBILENET_ERROR_INPUT UINT32_C(2)
#define OPENNPUX_CORAL_MOBILENET_ERROR_INVOKE UINT32_C(3)
#define OPENNPUX_CORAL_MOBILENET_ERROR_OUTPUT UINT32_C(4)

struct opennpux_coral_mobilenet_mailbox {
    uint32_t magic;
    uint32_t version;
    uint32_t state;
    uint32_t error_code;
    uint32_t cycle_low;
    uint32_t cycle_high;
    uint32_t output_count;
    int32_t output[OPENNPUX_CORAL_MOBILENET_OUTPUT_COUNT];
    uint32_t reserved[4];
};

#endif
